version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/testdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      
  h2-console:
    image: oscarfonts/h2
    ports:
      - "8081:8080"
    environment:
      - H2_OPTIONS=-ifNotExists
